name: Release kofr on Linux and MacOS

on:
  push:
    tags:
      - '*' 
env:
  CARGO_TERM_COLOR: always
  LINUX_BUILD_TARGET: x86_64-unknown-linux-musl
  MACOS_BUILD_TARGET: x86_64-apple-darwin
  BINARY_NAME: kofr

jobs:
  linux:
    name: build and release for linux
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@v2
      - name: install linux-musl
        run: sudo apt install musl-tools -y

      - name: Run cargo build --release
        uses: gmiam/rust-musl-action@master
        with:
          args: cargo build --target $LINUX_BUILD_TARGET --release
      
      - name: archive binary
        run: tar -czvf kofr-linux-amd64.tar.gz -C ./target/$LINUX_BUILD_TARGET/release $BINARY_NAME
      
      - uses: actions/upload-artifact@v3
        with:
          name: kofr-linux
          path: kofr-linux-amd64.tar.gz

  macos: 
    name: build and release for macos
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@v2
      
      - name: install rustup toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: $MACOS_BUILD_TARGET
      
      - name: build
        run: |
          ./ci/build_macos.sh
        shell: bash

      - name: archive binary
        run: tar -czvf kofr-darwin.tar.gz -C ./target/$MACOS_BUILD_TARGET/release $BINARY_NAME
      
      - uses: actions/upload-artifact@v3
        with:
          name: kofr-darwin
          path: kofr-darwin.tar.gz

  publish:
    needs: [linux, macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: kofr-linux

      - uses: actions/download-artifact@v2
        with:
          name: kofr-darwin

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            kofr-linux-amd64.tar.gz
            kofr-darwin.tar.gz